apps/goods/urls.py
from django.urls import path, re_path
from .views import GoodsDetailView, IndexView, GoodsTypeListView, AddCartView

app_name = 'goods'
urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),
    re_path(r'^detail/(?P<goods_id>\d+)/$', GoodsDetailView.as_view(), name='detail'),
    re_path(r'^type_list/(?P<type_id>\d+)/(?P<page_num>\d+)/', GoodsTypeListView.as_view(), name='list'),
    path('add_cart/', AddCartView.as_view(), name='add_cart'),
]

apps/order/urls.py
from django.urls import path, re_path
from .views import CreateOrderView, SubmitOrderView, AliPayView,\
    QueryTradeStatus, OrderEvaluate, OrderRightAwayView

app_name = 'order'
urlpatterns = [
    path('create_order/', CreateOrderView.as_view(), name='create_order'),
    path('right_away_order/', OrderRightAwayView.as_view(), name='right_away_order'),
    path('submit_order/', SubmitOrderView.as_view(), name='submit_order'),
    path('pay_order/', AliPayView.as_view(), name='pay_order'),
    path('query_order/', QueryTradeStatus.as_view(), name='query_order'),
    re_path(r'^evaluate_order/(?P<order_id>\d+)/', OrderEvaluate.as_view(), name='evaluate_order'),
]

daily_fresh/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from apps.goods.views import RedirectIndexView
urlpatterns = [
    path('prefix/admin/', admin.site.urls),
    path('prefix/search/', include('haystack.urls')),
    path('prefix/tinymce/', include('tinymce.urls')), # 富文本编辑器
    path('prefix/cart/', include('cart.urls')),
    path('prefix/goods/', include('goods.urls')),
    path('prefix/order/', include('order.urls')),
    path('prefix/user/', include('user.urls')),
    path('prefix/', RedirectIndexView.as_view()),
]

apps/goods/models.py
from django.db import models
from db.base_model import BaseModel
from tinymce.models import HTMLField
# Create your models here.


class GoodsType(BaseModel):
    '''商品种类表'''
    name = models.CharField(max_length=20, verbose_name='种类名称')
    logo = models.CharField(max_length=30, verbose_name='图标标识')
    image = models.ImageField(upload_to='type', verbose_name='商品类型图片')

    class Meta:
        db_table = 'df_goods_type'
        verbose_name = '商品种类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsSKU(BaseModel):
    '''商品SKU表'''
    status_choices = (
        (0, '下线'),
        (1, '上线'),
    )
    type = models.ForeignKey(
        'GoodsType',
        on_delete=models.CASCADE,
        verbose_name='商品种类')
    goods = models.ForeignKey(
        'Goods',
        on_delete=models.CASCADE,
        verbose_name='商品SPU')
    name = models.CharField(max_length=50, verbose_name='商品名称')
    desc = models.CharField(max_length=256, verbose_name='商品简介')
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='商品价格')
    unite = models.CharField(max_length=20, verbose_name='商品单位')
    image = models.ImageField(upload_to='goods', verbose_name='商品图片')
    stock = models.IntegerField(default=1, verbose_name='商品库存')
    sales = models.IntegerField(default=0, verbose_name='商品销量')
    status = models.SmallIntegerField(
        default=1,
        choices=status_choices,
        verbose_name='商品状态')

    class Meta:
        db_table = 'df_goods_sku'
        verbose_name = '商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Goods(BaseModel):
    '''商品SPU表'''
    name = models.CharField(max_length=50, verbose_name='商品SPU名称')
    detail = HTMLField(blank=True, verbose_name='商品详情')

    class Meta:
        db_table = 'df_goods'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsImage(BaseModel):
    '''商品图片模型表'''
    sku = models.ForeignKey(
        'GoodsSKU',
        on_delete=models.CASCADE,
        verbose_name='商品')
    image = models.ImageField(upload_to='goods', verbose_name='图片路径')

    class Meta:
        db_table = 'df_goods_image'
        verbose_name = '商品图片'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sku.name


class IndexGoodsBanner(BaseModel):
    '''首页轮播商品展示模型'''
    sku = models.ForeignKey(
        'GoodsSKU',
        on_delete=models.CASCADE,
        verbose_name='商品')
    image = models.ImageField(upload_to='banner', verbose_name='图片')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_banner'
        verbose_name = '首页轮播商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sku.name


class IndexTypeGoodsBanner(BaseModel):
    '''首页分类商品展示'''
    DISPLAY_TYPE_CHOICES = (
        (0, '标题'),
        (1, '图片'),
    )

    type = models.ForeignKey(
        'GoodsType',
        on_delete=models.CASCADE,
        verbose_name='商品类型')
    sku = models.ForeignKey(
        'GoodsSKU',
        on_delete=models.CASCADE,
        verbose_name='商品SKU')
    display_type = models.SmallIntegerField(
        default=1, choices=DISPLAY_TYPE_CHOICES, verbose_name='展示类型')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_type_goods'
        verbose_name = '主页分类展示商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sku.name


class IndexPromotionBanner(BaseModel):
    '''首页促销活动表'''
    name = models.CharField(max_length=20, verbose_name='活动名称')
    url = models.URLField(verbose_name='活动链接')
    image = models.ImageField(upload_to='banner', verbose_name='活动图片')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_promotion'
        verbose_name = '主页促销活动'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

apps/goods/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import View
from django.http import HttpResponse, JsonResponse
from apps.goods.models import GoodsSKU, GoodsType, GoodsImage, Goods, IndexGoodsBanner, IndexPromotionBanner, IndexTypeGoodsBanner
from apps.order.models import OrderGoods
from django.core.cache import cache
from django_redis import get_redis_connection
from django.core.paginator import Paginator, Page
from django.contrib.sessions.backends.base import SessionBase
from django.conf import settings
from haystack.generic_views import SearchView
import haystack.urls
# Create your views here.


class RedirectIndexView(View):
    def get(self, request):
        return redirect(reverse('goods:index'))


class IndexView(View):
    def get(self, request):
        if not request.user.is_authenticated: # 登录就返回index，没登录就返回index_static
            print('====>返回静态的首页')
            return render(request, 'static_index.html')

        print('====>获取查询数据库的首页')
        context = cache.get('index_cache')

        if context is None:  # 缓存不存在或者已过期
            print('缓存不存在，重新读取数据库设置缓存')
            goods_type_list = GoodsType.objects.all()
            goods_banner_list = IndexGoodsBanner.objects.all().order_by('index')
            goods_promotion_list = IndexPromotionBanner.objects.all().order_by('-index')

            for goods_type in goods_type_list:
                type_title_list = IndexTypeGoodsBanner.objects.filter(type=goods_type, display_type=0).order_by('index')
                type_image_list = IndexTypeGoodsBanner.objects.filter(type=goods_type, display_type=1).order_by('index')
                goods_type.type_title_list = type_title_list
                goods_type.type_image_list = type_image_list
            context = {'goods_type_list': goods_type_list,
                       'goods_banner_list': goods_banner_list,
                       'goods_promotion_list': goods_promotion_list}
            cache.set('index_cache', context, 3600)  # 缓存一个小时

        cart_count = 0
        if request.user.is_authenticated: #  读取缓存中购物车的记录
            con = get_redis_connection('default')
            cart_key = 'cart_id%s' % request.user.id
            cart_count = con.hlen(cart_key)

        context.update(cart_count=cart_count)

        return render(request, 'goods/index.html', context)


class GoodsDetailView(View):
    def get(self, request, goods_id):
        print('===>goods_id:', goods_id)
        try:
            goods_sku = GoodsSKU.objects.get(id=goods_id)
        except GoodsSKU.DoseNotExist:
            return redirect(reverse('goods:index'))
        new_goods_list = GoodsSKU.objects.all().exclude(id=goods_id).order_by('-create_time')[:2]
        type_goods_list = GoodsType.objects.all().order_by('id')
        goods_spu = goods_sku.goods
        evaluate_goods = goods_sku.ordergoods_set.exclude(comment__exact='')
        context = {
            'goods_sku': goods_sku,
            'new_goods_list': new_goods_list,
            'type_goods_list': type_goods_list,
            'evaluate_goods': evaluate_goods,
        }
        cart_count = 0
        if request.user.is_authenticated:  # 读取缓存中购物车的记录
            con = get_redis_connection('default')
            cart_key = 'cart_id%s' % request.user.id
            cart_count = con.hlen(cart_key)

            # 添加最近浏览，用sku的id做value
            browse_key = 'user_browse_%s' % request.user.id
            con.lrem(browse_key, 0, goods_id) # 先删除之前列表里面的goods id
            con.lpush(browse_key,  goods_id) # 再从左侧添加添加goods id
            if con.llen(browse_key) > 5:
                con.rpop(browse_key)

        context.update(cart_count=cart_count)

        return render(request, 'goods/detail.html', context)


class GoodsTypeListView(View):
    def get(self, request, type_id, page_num):
        print('====>type_id:', type_id)
        print('====>page_num:', page_num, type(page_num))
        new_goods_list = GoodsSKU.objects.all().order_by('-create_time')[:2]
        try:
            goods_type = GoodsType.objects.get(id=type_id)
        except GoodsType.DoesNotExist:
            return redirect(reverse('goods:index'))

        goods_sku_list = GoodsSKU.objects.filter(type=goods_type).order_by('id')
        type_goods_list = GoodsType.objects.all().order_by('id')

        paginator = Paginator(goods_sku_list, 8)
        page = paginator.get_page(int(page_num))  # 拿到对应的页对象,这个方法会自动处理超范围的页码

        context = {'new_goods_list': new_goods_list,
                   'goods_type': goods_type,
                   'goods_sku_list': goods_sku_list,
                   'type_goods_list': type_goods_list,
                   'page': page, }

        cart_count = 0
        if request.user.is_authenticated:  # 读取缓存中购物车的记录
            con = get_redis_connection('default')
            cart_key = 'cart_id%s' % request.user.id
            cart_count = con.hlen(cart_key)
        context.update(cart_count=cart_count)

        return render(request, 'goods/list.html', context)


def failed_msg(code, msg):
    return {
        'ret': 'failed',
        'code': code,
        'msg': msg,
    }


class AddCartView(View):
    '''没比较存库量，后续要处理一下，还有订单并发'''
    def post(self, request):
        goods_id = request.POST.get('goods_id')
        add_count = request.POST.get('add_count', 0)
        print('===>goods_id:', goods_id)
        print('===>add_count:', add_count)

        if goods_id is None:
            return JsonResponse(failed_msg('2', '商品ID缺失'))
        cart_count = 0
        if not request.user.is_authenticated:
            return JsonResponse(failed_msg('1', '用户未登录'))

        # todo 读取缓存中购物车的记录
        con = get_redis_connection('default')
        cart_key = 'cart_id%s' % request.user.id

        goods_field = con.hget(cart_key, goods_id) # 先读取，加一后再写进去,如果field找不到就直接写1
        print('====>goods_field:', goods_field)
        if goods_field:
            con.hset(cart_key, goods_id, int(goods_field) + int(add_count))
        else:
            con.hset(cart_key, goods_id, add_count)

        cart_count = con.hlen(cart_key)  # 最后再读取一次返回

        json_data = {'goods_count': cart_count}

        return JsonResponse(json_data)

apps/goods/templates/goods/detail.html
{% extends 'base_detail_list.html' %}
{% load static %}
{% block main_content %}
<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' goods_sku.goods.id 1 %}">{{goods_sku.type.name}}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{goods_sku.image.url}}"></div>

		<div class="goods_detail_list fr">
			<h3>{{goods_sku.name}}</h3>
			<p>{{goods_sku.desc}}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{goods_sku.price}}</em></span>
				<span class="show_unit">单  位：{{goods_sku.unite}}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<form action="{% url 'order:right_away_order' %}" method="post">
					{% csrf_token %}
						<input type="hidden" name="goods_id" value="{{goods_sku.id}}">
						<input type="number" name="goods_count" class="num_show fl" value="1">
					</form>
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
			<div class="total">总价：<em></em></div>
			<div class="operate_btn">
				<a href="javascript:buy_submit();" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
				{% for new_goods in new_goods_list %}
					<li>
						<a href="{% url 'goods:detail' new_goods.id %}"><img src="{{new_goods.image.url}}"></a>
						<h4><a href="{% url 'goods:detail' new_goods.id %}">{{new_goods.name}}</a></h4>
						<div class="prize">￥{{new_goods.price}}</div>
					</li>
				{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="goods_detail active">商品介绍</li>
				<li class="goods_evaluate">评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{goods_sku.goods.detail|safe}}</dd>
				</dl>
			</div>
			<div class="tab_evaluate">
				{% for evaluate_good in evaluate_goods %}
				<div class="evaluate_box">
					<span>评价时间:{{evaluate_good.update_time}}</span></br>
					<span>{{evaluate_good.comment}}</span>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
	<div class="for_goods_id">{{goods_sku.id}}</div>
{% endblock main_content %}

{% block bottom %}
  <div class="add_jump"></div>
{% endblock bottom %}
{% block bottomfiles %}
  <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
{% csrf_token %}
	<script type="text/javascript">
	$(function ($){
			$('.tab_evaluate').hide()
			var price = $('.show_pirze').children('em').text()
			price = parseFloat(price)
			var count = $('.num_show').val()
			count = parseInt(count)
			console.log('===>price:' + price)
			console.log('===>count:' + count)
			var tatol_price = price * count
			$('.total').children('em').text(tatol_price.toFixed(2))

			$('.add').click(function(){
				count += 1
				$('.num_show').val(count)
				tatol_price = count * price
				$('.total').children('em').text(tatol_price.toFixed(2))
			})

			$('.minus').click(function(){
				count -= 1
				if (count < 1) {
					count = 1
				}
				$('.num_show').val(count)
				tatol_price = count * price
				$('.total').children('em').text(tatol_price.toFixed(2))
			})
			$('.num_show').blur(function(){
				count = $('.num_show').val()
				count = parseInt(count)
				if (isNaN(count) || count < 1 || count > 999){
					count = 1
				}
				$('.num_show').val(count)
				console.log('====>count:'+ count)

				tatol_price = count * price
				$('.total').children('em').text(tatol_price.toFixed(2))
			})
		});
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;
		function csrfSafeMethod(method) {
			// these HTTP methods do not require CSRF protection
			return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
		}
		$('#add_cart').click(function(){
			var csrftoken = $("[name='csrfmiddlewaretoken']").val()
			$.ajaxSetup({
					beforeSend: function(xhr, settings) {
							if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
									xhr.setRequestHeader("X-CSRFToken", csrftoken);
							}
					}
			});
			$.post('/prefix/goods/add_cart/', {
					'goods_id': $('.for_goods_id').text(),
					'add_count': $('.num_show').val()
				}, function (data) {
					console.log('====>jsondata:')
					if (data['ret'] === 'failed' && data['code'] === '1') {
						location.href = '/prefix/user/login/'
						return
					}
					console.log(data)
					$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
					$(".add_jump").stop().animate({
						'left': $to_y+7,
						'top': $to_x+7},
						"fast", function() {
							$(".add_jump").fadeOut('fast',function(){
								$('#show_count').html(data.goods_count);
							});
					});
			})
		})
		$('.goods_detail').click(function(){
			console.log(11111)
			$('.tab_evaluate').hide()
			$('.tab_content').show()
			$(this).addClass('active')
			$('.goods_evaluate').removeClass('active')
		})
		$('.goods_evaluate').click(function(){
			console.log(22222)
			$('.tab_content').hide()
			$('.tab_evaluate').show()
			$(this).addClass('active')
			$('.goods_detail').removeClass('active')
		})
		function buy_submit(){
			$('form').submit()
		}
	</script>
{% endblock bottomfiles %}

apps/goods/templates/goods/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天生鲜{% endblock title %}
{% block topfiles %}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">有机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			{% for goods_type in goods_type_list %}
				<li><a href="{% url 'goods:list' goods_type.id 1 %}" class="{{goods_type.logo}}">{{goods_type.name}}</a></li>
			{% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
			{% for goods_banner in goods_banner_list %}
				<li><img src="{{goods_banner.image.url}}" alt="幻灯片"></li>
			{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
		{% for goods_promotion in goods_promotion_list %}
			<a href="{{goods_promotion.url}}"><img src="{{goods_promotion.image.url}}"></a>
		{% endfor %}
		</div>
	</div>
{% for goods_type in goods_type_list %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{goods_type.id}}">{{goods_type.name}}</h3>
			<div class="subtitle fl">
				<span>|</span>
			{% for type_title in goods_type.type_title_list %}
				<a href="#">{{type_title.sku.name}}</a>
			{% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{goods_type.image.url}}"></div>
			<ul class="goods_list fl">
			{% for type_image in goods_type.type_image_list %}
				<li>
					<h4><a href="{% url 'goods:detail' type_image.sku.id %}">{{type_image.sku.name}}</a></h4>
					<a href="{% url 'goods:detail' type_image.sku.id %}"><img src="{{type_image.sku.image.url}}"></a>
					<div class="prize">¥ {{type_image.sku.price}}</div>
				</li>
			{% endfor %}
			</ul>
		</div>
	</div>
{% endfor %}

{% endblock body %}

apps/goods/templates/goods/list.html
{% extends 'base_detail_list.html' %}
{% load static %}
{% block main_content %}
<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{goods_type.name}}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
				{% for new_goods in new_goods_list %}
					<li>
						<a href="{% url 'goods:detail' new_goods.id %}"><img src="{{new_goods.image.url}}"></a>
						<h4><a href="{% url 'goods:detail' new_goods.id %}">{{new_goods.name}}</a></h4>
						<div class="prize">￥{{new_goods.price}}</div>
					</li>
				{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="#">价格</a>
				<a href="#">人气</a>
			</div>

			<ul class="goods_type_list clearfix">
			{% for goods_sku in page.object_list %}
				<li>
					<a href="{% url 'goods:detail' goods_sku.id %}"><img src="{{goods_sku.image.url}}"></a>
					<h4><a href="{% url 'goods:detail' goods_sku.id %}">{{goods_sku.name}}</a></h4>
					<div class="operate">
						<span class="prize">￥{{goods_sku.price}}</span>
						<span class="unit">{{goods_sku.price}}/{{goods_sku.unite}}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
			{% endfor %}
			</ul>
			<div class="pagenation">
				<a href="#"><上一页</a>
			{% for page_num in page.paginator.page_range %}
				<a href="{% url 'goods:list' goods_type.id page_num %}" {% if page_num == page.number %}class="active"{% endif %}>{{page_num}}</a>
			{% endfor %}
				<a href="#">下一页></a>
			</div>
		</div>
	</div>
{% endblock main_content %}