apps/cart/urls.py
from django.urls import path
from .views import CartInfoView, DelCartView, UpdateCartView

app_name = 'cart'
urlpatterns = [
    path('info/', CartInfoView.as_view(), name='info'),
    path('cart_del/', DelCartView.as_view(), name='cart_del'),
    path('update/', UpdateCartView.as_view(), name='update'),
]

apps/goods/urls.py
from django.urls import path, re_path
from .views import GoodsDetailView, IndexView, GoodsTypeListView, AddCartView

app_name = 'goods'
urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),
    re_path(r'^detail/(?P<goods_id>\d+)/$', GoodsDetailView.as_view(), name='detail'),
    re_path(r'^type_list/(?P<type_id>\d+)/(?P<page_num>\d+)/', GoodsTypeListView.as_view(), name='list'),
    path('add_cart/', AddCartView.as_view(), name='add_cart'),
]

apps/user/urls.py
from django.urls import path, re_path
from .views import LoginView, RegisterView, ActiveAccount, \
    TestView,UserInfo, UserOrder, UserAddress, userinfo, LogoutView, SetDefaultAddress

app_name = 'user'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    re_path(r'^active_account/(?P<token>.*)/?$', ActiveAccount.as_view(), name='active_account'),
    path('', UserInfo.as_view(), name='info'),
    # path('', userinfo, name='info'),
    re_path(r'^order/(?P<page_num>\d+)/', UserOrder.as_view(), name='order'),
    path('address/', UserAddress.as_view(), name='address'),
    path('address/set_default/', SetDefaultAddress.as_view(), name='set_default'),
    path('test/', TestView.as_view(), name='test'),

]

daily_fresh/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from apps.goods.views import RedirectIndexView
urlpatterns = [
    path('prefix/admin/', admin.site.urls),
    path('prefix/search/', include('haystack.urls')),
    path('prefix/tinymce/', include('tinymce.urls')), # 富文本编辑器
    path('prefix/cart/', include('cart.urls')),
    path('prefix/goods/', include('goods.urls')),
    path('prefix/order/', include('order.urls')),
    path('prefix/user/', include('user.urls')),
    path('prefix/', RedirectIndexView.as_view()),
]

apps/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{# 首页 详情页 列表页 注册 登录 #}
<head>
	{% load static %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
  {% block topfiles %}
	{% endblock topfiles %}
</head>
<body>
{% block header_cont %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated and not static_html %}
				<div class="login_btn fl">
					欢迎您：<em>{{user.username}}</em>
					<span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:info' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header_cont %}

{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<form action="/prefix/search" method="get">
				<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
				<input type="submit" class="input_btn fr" name="" value="搜索">
			</form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:info' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{cart_count}}</div>
		</div>
	</div>
{% endblock search_bar %}

{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 河南快客金融服务有限公司 All Rights Reserved</p>
		<p>电话：19903713520    郑州市郑东新区平安大道186号正商环湖国际8层</p>
	</div>
{% block bottom %}{% endblock bottom %}
{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

apps/templates/base_detail_list.html
{% extends 'base.html' %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					{% for type_goods in type_goods_list %}
					<li><a href="{% url 'goods:list' type_goods.id 1 %}" class="{{type_goods.logo}}">{{type_goods.name}}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
  {% block main_content %}{% endblock main_content %}
{% endblock body %}

apps/templates/base_no_cart.html
{# 购物车 提交订单 用户订单 #}
{% extends 'base.html' %}
{% load static %}
{% block search_bar %}
<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
			<form action="/prefix/search" method="get">
				<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
				<input type="submit" class="input_btn fr" name="" value="搜索">
			</form>
		</div>
	</div>
{% endblock search_bar %}

apps/templates/base_user_center.html
{# 用户中心 #}
{% extends 'base_no_cart.html' %}
{% load static %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:info' %}" {% if page == 'info' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
  {% block right_content %}{% endblock right_content %}
</div>
{% endblock body %}