apps/cart/urls.py
from django.urls import path
from .views import CartInfoView, DelCartView, UpdateCartView

app_name = 'cart'
urlpatterns = [
    path('info/', CartInfoView.as_view(), name='info'),
    path('cart_del/', DelCartView.as_view(), name='cart_del'),
    path('update/', UpdateCartView.as_view(), name='update'),
]

apps/order/urls.py
from django.urls import path, re_path
from .views import CreateOrderView, SubmitOrderView, AliPayView,\
    QueryTradeStatus, OrderEvaluate, OrderRightAwayView

app_name = 'order'
urlpatterns = [
    path('create_order/', CreateOrderView.as_view(), name='create_order'),
    path('right_away_order/', OrderRightAwayView.as_view(), name='right_away_order'),
    path('submit_order/', SubmitOrderView.as_view(), name='submit_order'),
    path('pay_order/', AliPayView.as_view(), name='pay_order'),
    path('query_order/', QueryTradeStatus.as_view(), name='query_order'),
    re_path(r'^evaluate_order/(?P<order_id>\d+)/', OrderEvaluate.as_view(), name='evaluate_order'),
]

daily_fresh/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from apps.goods.views import RedirectIndexView
urlpatterns = [
    path('prefix/admin/', admin.site.urls),
    path('prefix/search/', include('haystack.urls')),
    path('prefix/tinymce/', include('tinymce.urls')), # 富文本编辑器
    path('prefix/cart/', include('cart.urls')),
    path('prefix/goods/', include('goods.urls')),
    path('prefix/order/', include('order.urls')),
    path('prefix/user/', include('user.urls')),
    path('prefix/', RedirectIndexView.as_view()),
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, JsonResponse
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django_redis import get_redis_connection
from apps.goods.models import GoodsSKU
# Create your views here.


class CartInfoView(LoginRequiredMixin, View):
    def get(self, request):
        con = get_redis_connection('default')
        cart_key = 'cart_id%s' % request.user.id
        cart_list = con.hgetall(cart_key)
        print('====>cart_list:', cart_list)
        goods_sku_list = list()
        total_count = 0
        for key in cart_list:  # 遍历购物车
            print('key: ', key.decode(), '   -value: ', cart_list[key].decode())
            try:
                goods_sku = GoodsSKU.objects.get(id=key.decode())  # 去除购物车的sku对象
            except GoodsSKU.DoesNotExist:
                continue
            goods_sku.cart_count = cart_list[key].decode()
            goods_sku_list.append(goods_sku)
            total_count += int(cart_list[key].decode())

        context = {
            'goods_sku_list': goods_sku_list,
            'total_count': total_count,
        }
        return render(request, 'cart/cart.html', context)


def failed_msg(code, msg):
    return {
        'ret': 'failed',
        'code': code,
        'msg': msg,
    }


class UpdateCartView(View):
    def post(self, request):
        context = {
            'ret': 'failed'
        }

        if not request.user.is_authenticated:
            return JsonResponse(failed_msg('1', '用户未登录'))

        goods_id = request.POST.get('cart_goods_id', None)
        goods_count = request.POST.get('cart_goods_count', None)
        print('===>goods_id:', goods_id)
        print('==>DelCartView-post:', request.POST)
        try:
            goods_count = int(goods_count)
        except ValueError:
            goods_count = None
        if goods_id is not None and goods_count is not None:
            cart_key = 'cart_id%s' % request.user.id
            conn = get_redis_connection('default')
            conn.hset(cart_key, goods_id, goods_count)
            context.update(ret='success')

        return JsonResponse(context)


class DelCartView(View):
    def post(self, request):
        context = {
            'ret': 'failed'
        }
        if request.user.is_authenticated:
            goods_id = request.POST.get('cart_goods_id', None)
            print('===>goods_id:', goods_id)
            print('==>DelCartView-post:', request.POST)
            if goods_id is not None:
                cart_key = 'cart_id%s' % request.user.id
                conn = get_redis_connection('default')
                conn.hdel(cart_key, goods_id)
                context.update(ret='success')

        return JsonResponse(context)

apps/cart/templates/cart/cart.html
{% extends 'base_no_cart.html' %}
{% load static %}
{% block page_title %}
购物车
{% endblock page_title %}
{% block body %}
<div class="total_count">全部商品<em>{{total_count}}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>

	<form action="{% url 'order:create_order' %}" method="post">
	{% csrf_token %}
	{% for goods_sku in goods_sku_list %}
		<ul class="cart_list_td clearfix">
			<li class="col01"><input type="checkbox" name="sku_id" value="{{goods_sku.id}}" checked></li>
			<li class="col02"><img src="{{goods_sku.image.url}}"></li>
			<li class="col03">{{goods_sku.name}}<br><em>{{goods_sku.price}}元/{{goods_sku.unite}}</em></li>
			<li class="col04">{{goods_sku.unite}}</li>
			<li class="col05">{{goods_sku.price}}元</li>
			<li class="col06">
				<div class="num_add">
					<a href="javascript:;" class="add fl">+</a>
					<input type="number" class="num_show fl" value="{{goods_sku.cart_count}}">
					<a href="javascript:;" class="minus fl">-</a>
				</div>
			</li>
			<li class="col07"><span></span>元</li>
			<li class="col08"><a href="javascript:;">删除</a></li>
			<li id="for_goods_id" style="display:none">{{goods_sku.id}}</li>
		</ul>
	{% endfor %}

		<ul class="settlements">
			<li class="col01"><input type="checkbox" name="" checked></li>
			<li class="col02">全选</li>
			<li class="col03">合计(不含运费)：<span>¥</span><em>0</em><br>共计<b>{{total_count}}</b>件商品</li>
			<li class="col04"><a href="javascript:traggerSubmit();">去结算</a></li>
		</ul>
	</form>
{% endblock body %}
{% block bottomfiles %}
  <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
{% csrf_token %}
	<script type="text/javascript">
		$(function ($){
			var list1 = $('.cart_list_td')
			$.each($('.cart_list_td'), function (index, value) {
				// console.log(index, value)

				var price = $(this).children('.col05').text()
				price = parseFloat(price)
				var count = $(this).children('.col06').find("input[type='number']").val()
				count = parseInt(count)
				var tatol_price = price * count
				$(this).children('.col07').children('span').text(tatol_price.toFixed(2))

				// add = $(this).children('.col06').find('.add').text()
				// console.log(add)

				$(this).children('.col06').find('.add').click(function(){
					count += 1
					var self = $(this)
					var param = {
						'cart_goods_id': $('.cart_list_td').eq(index).children('#for_goods_id').text(),
						'cart_goods_count': count
					}
					ajaxPost('/prefix/cart/update/', param, function(){
						self.next("input[type='number']").val(count)
						tatol_price = count * price
						tmp = $(this).parent('.num_add').parent('.col06').next('.col07').children('span').text(tatol_price.toFixed(2))
						total_price()
					}, function(){
						location.href = '/prefix/goods/index'
					})
				})
				$(this).children('.col06').find('.minus').click(function(){
					count -= 1
					if (count < 1) {
						count = 1
					}
					var self = $(this)
					var param = {
						'cart_goods_id': $('.cart_list_td').eq(index).children('#for_goods_id').text(),
						'cart_goods_count': count
					}
					ajaxPost('/prefix/cart/update/', param, function(){
						self.prev("input[type='number']").val(count)
						tatol_price = count * price
						tmp = self.parent('.num_add').parent('.col06').next('.col07').children('span').text(tatol_price.toFixed(2))
						total_price()
					}, function(){
						location.href = '/prefix/goods/index'
					})
				})
				var per_count
				$(this).find('.num_show').focus(function(){
					per_count = parseInt($(this).val())
				})
				$(this).find('.num_show').blur(function(){
					count = parseInt($(this).val())
					if (isNaN(count) || count < 1 || count > 999){
						count = per_count
					}
					var self = $(this)
					var param = {
						'cart_goods_id': $('.cart_list_td').eq(index).children('#for_goods_id').text(),
						'cart_goods_count': count
					}
					ajaxPost('/prefix/cart/update/', param, function(){
						self.val(count)
						tatol_price = parseInt(count) * price
						self.parents('li.col06').next().children('span').text(tatol_price.toFixed(2))
						total_price()
					}, function(){
						location.href = '/prefix/goods/index'
					})
				})
				$(this).children('.col01').children("input[type='checkbox']").change(function() {
					// a = $(this).prop('checked')
					// console.log(a)
					total_price()
				})
				$(this).children('.col08').children('a').click(function(){
					var self = $(this)
					var param = {
						'cart_goods_id': $('.cart_list_td').eq(index).children('#for_goods_id').text()
					}
					ajaxPost('/prefix/cart/cart_del/', param, function(){
						self.parents('ul').remove()
						total_price()
					}, function(){
						location.href = '/prefix/goods/index'
					})
				})
			})
			function csrfSafeMethod(method) {
				// these HTTP methods do not require CSRF protection
				return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
			}
			function ajaxPost(url, param, successFun, failFun) {
				var csrftoken = $("[name='csrfmiddlewaretoken']").val()
				$.ajaxSetup({
					beforeSend: function(xhr, settings) {
						if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
								xhr.setRequestHeader("X-CSRFToken", csrftoken);
						}
					}
				});
				$.post(url, param, function (data) {
					console.log('====>jsondata:')
					console.log(data)
					if(data['ret'] === 'failed') {
						failFun()
					}else if (data['ret'] === 'success'){
						successFun()
					}
				})
			}
			// 全选
			$('.settlements').find(':checkbox').change(function(){
				var is_checked = $(this).prop('checked')
				$('.cart_list_td').find(':checkbox').each(function(index, value){
					$(this).prop('checked', is_checked)
				})
				total_price()
			})
			// 算总价格
			total_price()
		});
		function total_price(){
			var total_price = 0
			var total_count = 0
			$.each($('.cart_list_td'), function (index, value) {
				if ($(this).children('.col01').children("input[type='checkbox']").prop('checked')){
					var price = $(this).children('.col07').children('span').text()
					price = parseFloat(price)
					total_price += price
					var count = $(this).children('.col06').find("input[type='number']").val()
					count = parseInt(count)
					total_count += count
				}
			})
			$('.settlements').children('li.col03').children('em').text(total_price.toFixed(2))
			$('.settlements').children('li.col03').children('b').text(total_count)
			$('.total_count').children('em').text(total_count)
		}
		function traggerSubmit(){
			$('form').submit()
		}
	</script>
{% endblock bottomfiles %}