apps/goods/urls.py
from django.urls import path, re_path
from .views import GoodsDetailView, IndexView, GoodsTypeListView, AddCartView

app_name = 'goods'
urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),
    re_path(r'^detail/(?P<goods_id>\d+)/$', GoodsDetailView.as_view(), name='detail'),
    re_path(r'^type_list/(?P<type_id>\d+)/(?P<page_num>\d+)/', GoodsTypeListView.as_view(), name='list'),
    path('add_cart/', AddCartView.as_view(), name='add_cart'),
]

apps/user/urls.py
from django.urls import path, re_path
from .views import LoginView, RegisterView, ActiveAccount, \
    TestView,UserInfo, UserOrder, UserAddress, userinfo, LogoutView, SetDefaultAddress

app_name = 'user'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    re_path(r'^active_account/(?P<token>.*)/?$', ActiveAccount.as_view(), name='active_account'),
    path('', UserInfo.as_view(), name='info'),
    # path('', userinfo, name='info'),
    re_path(r'^order/(?P<page_num>\d+)/', UserOrder.as_view(), name='order'),
    path('address/', UserAddress.as_view(), name='address'),
    path('address/set_default/', SetDefaultAddress.as_view(), name='set_default'),
    path('test/', TestView.as_view(), name='test'),

]

daily_fresh/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from apps.goods.views import RedirectIndexView
urlpatterns = [
    path('prefix/admin/', admin.site.urls),
    path('prefix/search/', include('haystack.urls')),
    path('prefix/tinymce/', include('tinymce.urls')), # 富文本编辑器
    path('prefix/cart/', include('cart.urls')),
    path('prefix/goods/', include('goods.urls')),
    path('prefix/order/', include('order.urls')),
    path('prefix/user/', include('user.urls')),
    path('prefix/', RedirectIndexView.as_view()),
]

apps/order/models.py
from django.db import models
from db.base_model import BaseModel
# Create your models here.


class OrderInfo(BaseModel):
    '''订单模型类'''
    PAY_METHOD_CHOICES = (
        (1, '货到付款'),
        (2, '微信支付'),
        (3, '支付宝'),
        (4, '银联支付'),
    )

    ORDER_STATUS_CHOICS = (
        (1, '待支付'),
        (2, '待发货'),
        (3, '待收货'),
        (4, '待评价'),
        (5, '已完成')
    )
    ORDER_STATUS = {
        1: '待支付',
        2: '待发货',
        3: '待收货',
        4: '待评价',
        5: '已完成',
    }

    order_id = models.CharField(max_length=128, primary_key=True, verbose_name='订单ID')
    user = models.ForeignKey('user.User', on_delete=models.CASCADE, verbose_name='用户')
    addr = models.ForeignKey('user.Address', on_delete=models.CASCADE, verbose_name='地址')
    pay_method = models.SmallIntegerField(default=3, choices=PAY_METHOD_CHOICES, verbose_name='支付方式')
    total_count = models.IntegerField(default=1, verbose_name='商品数量')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品总价')
    transit_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='订单运费')
    order_status = models.SmallIntegerField(default=1, choices=ORDER_STATUS_CHOICS, verbose_name='订单状态')
    trade_no = models.CharField(max_length=128, verbose_name='支付编号')

    class Meta:
        db_table = 'df_order_info'
        verbose_name = '订单'
        verbose_name_plural = verbose_name


class OrderGoods(BaseModel):
    '''订单商品表'''
    order = models.ForeignKey('OrderInfo', on_delete=models.CASCADE, verbose_name='订单')
    sku = models.ForeignKey('goods.GoodsSKU', on_delete=models.CASCADE, verbose_name='商品SKU')
    count = models.IntegerField(default=1, verbose_name='商品数目')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    comment = models.CharField(max_length=256, verbose_name='评论')

    class Meta:
        db_table = 'df_order_goods'
        verbose_name = '订单商品'
        verbose_name_plural = verbose_name

apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from db.base_model import BaseModel

# Create your models here.


class User(AbstractUser, BaseModel):
    '''用户基本模型，直接继承了Django的用户认证模型'''

    class Meta:
        db_table = 'df_user'
        verbose_name = '用户'
        verbose_name_plural = verbose_name


class Address(BaseModel):
    '''地址模型类
        1.收件人 2.收件地址 3.邮编 4.联系方式 5.是否默认 6.用户ID
    '''
    user =models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='所属账户')
    receiver = models.CharField(max_length=20, verbose_name='收件人')
    addr = models.CharField(max_length=256, verbose_name='收件地址')
    zip_code = models.CharField(max_length=6, verbose_name='邮编地址')
    phone = models.CharField(max_length=11, verbose_name='联系电话')
    is_default = models.BooleanField(default=False, verbose_name='是否默认地址')

    class Meta:
        db_table = 'df_address'
        verbose_name = '地址'
        verbose_name_plural = verbose_name

apps/user/views.py
from django.shortcuts import render, reverse, redirect
from django.views.generic import View
from apps.user.models import User
from apps.goods.models import GoodsType, GoodsSKU
from apps.user.models import Address
from apps.order.models import OrderGoods, OrderInfo
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from django.conf import settings
from itsdangerous import SignatureExpired
from django.http import HttpResponse, HttpRequest, JsonResponse
from apps.user.tasks import send_register_active_mail
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.contrib.auth.mixins import LoginRequiredMixin
from django_redis import get_redis_connection
from django.core.paginator import Paginator


class LoginView(View):

    def get(self, request):
        if 'username' in request.COOKIES:
            user_name = request.COOKIES.get('username')
            checked = 'checked'
        else:
            user_name = ''
            checked = ''

        return render(request, 'user/login.html',
                      {'username': user_name, 'checked': checked})

    def post(self, request):
        print(request.POST)
        user_name = request.POST['username']
        password = request.POST['pwd']
        print('===>username:', user_name)
        print('===>passphrase:', password, ' and type is: ', type(password))
        data_error = None
        if not all([user_name, password]):
            data_error = {'error_msg': '请填写完整信息'}

        each_user = User.objects.filter(username=user_name)
        print('=>each_user:', each_user)
        is_active = 1
        if each_user.count() == 1:
            is_active = each_user.first().is_active

        user = authenticate(request, username=user_name, password=password)
        print('----->', user)
        if user is not None:
            login(request, user)
            print('get:', request.GET)

            redirect_url = request.GET.get('next', reverse('goods:index'))
            response = redirect(redirect_url)

            if request.POST.get('remember') == 'on':
                response.set_cookie('username', user_name, 14 * 24 * 3600)
            else:
                response.delete_cookie('username')
            return response
        else:
            if is_active == 1:
                data_error = {'error_msg': '用户名和密码错误'}
            else:
                data_error = {'error_msg': '该用户还未激活'}
        return render(request, 'user/login.html', data_error)
        # return HttpResponse(data_error.values())


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect(reverse('goods:index'))


class RegisterView(View):
    def get(self, request):
        # print(request.scheme)
        # print('request.META-HTTP_HOST------->')
        # print(request.META['HTTP_HOST'])
        return render(request, 'user/register.html')

    def post(self, request):
        print(request.POST)
        reg_data = request.POST
        data_error = None
        if not all([reg_data['user_name'], reg_data['email'],
                    reg_data['pwd'], reg_data['cpwd']]):
            data_error = {'error_msg': '请填写完整信息'}
        allow = reg_data.get('allow')
        if allow != 'on':
            data_error = {'error_msg': '请勾选使用协议'}

        try:
            reg_user = User.objects.get(username=reg_data['user_name'])
        except User.DoesNotExist:
            reg_user = None

        if reg_user:
            data_error = {'error_msg': '用户名已存在'}

        if data_error:
            return render(request, 'user/register.html', data_error)

        print(
            '====>pwd:',
            reg_data['pwd'],
            ' and type is: ',
            type(
                reg_data['pwd']))

        reg_user = User.objects.create_user(username=reg_data['user_name'],
                                            email=reg_data['email'],
                                            password=reg_data['pwd'])
        reg_user.is_active = 0
        reg_user.save()

        serializer = Serializer(settings.SECRET_KEY)
        info = {'confirm': reg_user.id}
        token = serializer.dumps(info)
        token = token.decode()
        host = request.META['HTTP_HOST']

        # send_register_active_mail([reg_data['email']], reg_user.username, token)
        send_register_active_mail.delay(
            [reg_data['email']], reg_user.username, token, host)

        return render(request, 'user/reg_success.html')


class ActiveAccount(View):
    def get(self, request, token):
        serializer = Serializer(settings.SECRET_KEY)
        try:
            ob = serializer.loads(token)
            user = User.objects.get(id=ob['confirm'])
            user.is_active = 1
            user.save()
            return redirect(reverse('user:login'))
        except SignatureExpired:
            return HttpResponse('<h1>激活链接已过期</h1>')


@login_required(login_url='/user/register')
def userinfo(request):
    print('====>session time:', cache.ttl(
        'django.contrib.sessions.cachequmpbccpxasfweqeh6zb6c8q7nejbtfh'))
    return render(request, 'user/user_center_info.html', {'page': 'info'})


class UserInfo(LoginRequiredMixin, View):
    # login_url = '/user/register'
    # redirect_field_name = 'redirect_to' # 改变参数的默认key值，默认是next
    def get(self, request):
        print('==>user:', request.user, type(request.user))

        con = get_redis_connection('default')
        recent_list = con.lrange('user_browse_%s' % request.user.id, 0, -1)
        print('====>recent_list:', recent_list)
        goods_recently_list = list()
        for goods_id in recent_list:
            try:
                goods_sku = GoodsSKU.objects.get(id=goods_id)
                goods_recently_list.append(goods_sku)
            except GoodsSKU.DoesNotExist:
                print('===>not exist, continue')
                continue

        return render(request, 'user/user_center_info.html',
                      {'page': 'info', 'goods_recently_list': goods_recently_list})


class UserOrder(LoginRequiredMixin, View):
    def get(self, request, page_num):
        # order_user = User.objects.get(id=request.user.id)
        user_order_queryset = request.user.orderinfo_set.all().order_by('-create_time')

        paginator = Paginator(user_order_queryset, 3)

        try:
            page_num = int(page_num)
        except ValueError:
            page_num = 1

        #  todo 这里加一个if elif的处理是为了自己生成显示的页码
        if page_num <= 0:  #  这里加这个处理主要是下面这个方法处理0一下的页码为最大页码
            page_num = 1
        elif page_num > paginator.num_pages:
            page_num = paginator.num_pages

        order_page = paginator.get_page(page_num)

        for per_order in order_page:
            per_order.payment_status = OrderInfo.ORDER_STATUS[per_order.order_status]

        total_pages = paginator.num_pages
        if total_pages < 5:
            pages = range(1, total_pages + 1)
        elif page_num <= 3:
            pages = range(1, 6)
        elif total_pages - page_num <= 2:
            pages = range(total_pages - 4, total_pages + 1)
        else:
            pages = range(page_num - 2, page_num + 3)

        context = {
            'user_order_queryset': order_page,
            'pages': pages,
        }

        return render(request,
                      'user/user_center_order.html', context)


class UserAddress(LoginRequiredMixin, View):
    def get(self, request):
        try:
            address_user = User.objects.get(id=request.user.id)
        except User.DoesNotExist:
            return HttpResponse('找不到该用户')

        address_list = address_user.address_set.all()  # 读取该用户下面的所有地址
        try:
            default_address = address_list.get(is_default=True)  # 读取默认的那个地址
        except Address.DoesNotExist:
            default_address = None
        return render(request,
                      'user/user_center_site.html',
                      {'address_list': address_list,
                       'default_address': default_address})

    def post(self, request):
        receiver = request.POST.get('receiver', None)
        detail_address = request.POST.get('detail_address', None)
        zip_post = request.POST.get('zip_post', None)
        phone_num = request.POST.get('phone_num', None)

        context = {'ret': 'failed'}
        try:
            user = User.objects.get(id=request.user.id)
        except User.DoesNotExist:
            return JsonResponse(context)

        if all([receiver, detail_address, phone_num]):
            new_address = Address.objects.create(
                user=user,
                receiver=receiver,
                addr=detail_address,
                zip_code=zip_post,
                phone=phone_num,
                is_default=False)

            new_address.save()
            context = {'ret': 'success'}

        return JsonResponse(context)


class SetDefaultAddress(View):
    def post(self, request):
        context = {'ret': 'failed'}
        if not request.user.is_authenticated:
            return JsonResponse(context)

        try:
            address_user = User.objects.get(id=request.user.id)
        except User.DoesNotExist:
            return JsonResponse(context)

        address_id = request.POST.get('address_id', None)
        if address_id:
            try:
                last_default_address = address_user.address_set.get(
                    is_default=True)
            except Address.DoesNotExist:
                last_default_address = None

            if last_default_address is not None:
                last_default_address.is_default = False
                last_default_address.save()

            try:
                default_address = Address.objects.get(id=address_id)
            except Address.DoesNotExist:
                return JsonResponse(context)
            default_address.is_default = True

apps/user/templates/user/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天生鲜{% endblock title %}
{% block topfiles %}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">有机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			{% for goods_type in goods_type_list %}
				<li><a href="#" class="{{goods_type.logo}}">{{goods_type.name}}</a></li>
			{% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
			{% for goods_banner in goods_banner_list %}
				<li><img src="{{goods_banner.image.url}}" alt="幻灯片"></li>
			{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
		{% for goods_promotion in goods_promotion_list %}
			<a href="{{goods_promotion.url}}"><img src="{{goods_promotion.image.url}}"></a>
		{% endfor %}
		</div>
	</div>
{% for goods_type in goods_type_list %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{goods_type.id}}">{{goods_type.name}}</h3>
			<div class="subtitle fl">
				<span>|</span>
			{% for type_title in goods_type.type_title_list %}
				<a href="#">{{type_title.sku.name}}</a>
			{% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{goods_type.image.url}}"></div>
			<ul class="goods_list fl">
			{% for type_image in goods_type.type_image_list %}
				<li>
					<h4><a href="#">{{type_image.sku.name}}</a></h4>
					<a href="#"><img src="{{type_image.sku.image.url}}"></a>
					<div class="prize">¥ {{type_image.sku.price}}</div>
				</li>
			{% endfor %}
			</ul>
		</div>
	</div>
{% endfor %}

{% endblock body %}

apps/user/templates/user/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天生鲜-登录{% endblock title %}

{% block header_cont %}{% endblock header_cont %}
{% block search_bar %}{% endblock search_bar %}

{% block body %}
<div class="login_top clearfix">
		<a href="{% url 'goods:index' %}" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{username}}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{checked}}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
							{% if error_msg %}
								<p style="color:pink;">{{error_msg}}</p>
							{% endif %}
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

apps/user/templates/user/reg_success.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
  {% load static %}
  <h1>恭喜您注册成功，请在邮箱点击激活链接后去登录</h1>
  <strong>已经在邮件中激活, <a href="{% url 'user:login' %}">马上登录</a></strong>
</body>
</html>

apps/user/templates/user/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天生鲜-注册{% endblock title %}
{% block topfiles %}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock topfiles %}

{% block header_cont %}{% endblock header_cont %}
{% block search_bar %}{% endblock search_bar %}

{% block body %}
<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url 'user:register' %}" method="post">
					{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
					<li class="reg_sub">
						{% if error_msg %}
							<span style="color:pink;">{{error_msg}}</span>
						{% endif %}
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>
{% endblock body %}

apps/user/templates/user/user_center_info.html
{% extends 'base_user_center.html' %}
{% load static %}
{% block right_content %}
<div class="right_content clearfix">
	<div class="info_con clearfix">
		<h3 class="common_title2">基本信息</h3>
		<ul class="user_info_list">
		<li><span>用户名：</span>18210569700</li>
		<li><span>联系方式：</span>18210569700</li>
		<li><span>联系地址：</span>北京市昌平区</li>
		</ul>
	</div>
	<h3 class="common_title2">最近浏览</h3>
	<div class="has_view_list">
		<ul class="goods_type_list clearfix">
		{% for goods_recently in goods_recently_list %}
			<li>
				<a href="{% url 'goods:detail' goods_recently.id %}"><img src="{{goods_recently.image.url}}"></a>
				<h4><a href="{% url 'goods:detail' goods_recently.id %}">{{goods_recently.name}}</a></h4>
				<div class="operate">
					<span class="prize">￥{{goods_recently.price}}</span>
					<span class="unit">16.80/{{goods_recently.unite}}</span>
					<a href="#" class="add_goods" title="加入购物车"></a>
				</div>
			</li>
		{% endfor %}
		</ul>
	</div>
</div>
{% endblock right_content %}

apps/user/templates/user/user_center_order.html
{% extends 'base_user_center.html' %}
{% load static %}
{% block right_content %}
<div class="right_content clearfix">
	<h3 class="common_title2">全部订单</h3>
	{% for order_info in user_order_queryset %}
	<ul class="order_list_th w978 clearfix">
		<li class="col01">{{order_info.create_time}}</li>
		<li class="col02">订单号：{{order_info.order_id}}</li>
		<li class="col02 stress">{{order_info.payment_status}}</li>
	</ul>

	<table class="order_list_table w980">
		<tbody>
			<tr>
				<td width="55%">
					{% for order_goods in order_info.ordergoods_set.all %}
					<ul class="order_goods_list clearfix">
						<li class="col01"><a href="{% url 'goods:detail' order_goods.sku.id %}"><img src="{{order_goods.sku.image.url}}"></a></li>
						<li class="col02">{{order_goods.sku.name}}<em>{{order_goods.sku.price}}元/{{order_goods.sku.unite}}</em></li>
						<li class="col03">{{order_goods.count}}</li>
						<li class="col04">{{order_goods.price}}元</li>
					</ul>
					{% endfor %}
				</td>
				<td width="15%">{{order_info.total_price}}元</td>
				<td width="15%">{{order_info.payment_status}}</td>
				<td width="15%">
					<a href="javascript:" orderId="{{order_info.order_id}}" order_status="{{order_info.order_status}}" class="oper_btn">
					{% if order_info.order_status == 4 %}
						去评价
					{% elif order_info.order_status == 5 %}
						已完成
					{% else %}
						去付款
					{% endif %}
					</a>
				</td>
			</tr>
		</tbody>
	</table>
	{% endfor %}


	<div class="pagenation">
		{% if user_order_queryset.has_previous %}
		<a href="{% url 'user:order' user_order_queryset.previous_page_number %}"><上一页</a>
		{% endif %}
		{% for pindex in pages %}
			{% if pindex == user_order_queryset.number %}
				<a href="{% url 'user:order' pindex %}" class="active">{{pindex}}</a>
			{% else %}
				<a href="{% url 'user:order' pindex %}">{{pindex}}</a>
			{% endif %}
		{% endfor %}
		{% if user_order_queryset.has_next %}
		<a href="{% url 'user:order' user_order_queryset.next_page_number %}"><下一页</a>
		{% endif %}
	</div>
</div>
{% endblock right_content %}
{% block bottomfiles %}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
{% csrf_token %}
	<script type="text/javascript">
		$(function(){
			$('.oper_btn').click(function(){
				console.log('===>order_status:' + $(this).attr('order_status'))
				console.log(typeof($(this).attr('order_status')))
				if ($(this).attr('order_status') === '1') {
					var self = $(this)
					var param = {
						'order_id': $(this).attr('orderId')
					}
					ajaxPost('/prefix/order/pay_order/', param, function(data){
						console.log(data)
						window.open(data['ali_url'])
						$.get('/prefix/order/query_order/', param, function(data){
							if (data['code'] === '0') {
								window.location.reload()
							} else {
								alert(data['msg'])
							}
						})
					}, function(data){
						alert(data['msg'])
					})
				} else if ($(this).attr('order_status') === '4') {
						location.href = '/prefix/order/evaluate_order/' + $(this).attr('orderId') + '/'
				}
			})
			function csrfSafeMethod(method) {
				// these HTTP methods do not require CSRF protection
				return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
			}
			function ajaxPost(url, param, successFun, failFun) {
				var csrftoken = $("[name='csrfmiddlewaretoken']").val()
				$.ajaxSetup({
					beforeSend: function(xhr, settings) {
						if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
								xhr.setRequestHeader("X-CSRFToken", csrftoken);
						}
					}
				});
				$.post(url, param, function (data) {
					console.log(data)
					if(data['ret'] === 'failed') {
						failFun(data)
					}else if (data['ret'] === 'success'){
						successFun(data)
					}
				})
			}
		})
	</script>
{% endblock bottomfiles %}

apps/user/templates/user/user_order_comment.html
{% extends 'base_user_center.html' %}
{% load static %}
{% block right_content %}
<div class="right_content clearfix">
	<h3 class="common_title2">全部订单</h3>
	<ul class="order_list_th w978 clearfix">
		<li class="col01">{{evaluate_order.create_time}}</li>
		<li class="col02">订单号：{{evaluate_order.order_id}}</li>
		<li class="col02 stress">{{evaluate_order.payment_status}}</li>
	</ul>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="hidden" name='order_id' value="{{evaluate_order.order_id}}">
    <input type="hidden" name='total_count' value="{{evaluate_order.ordergoods_set.all|length}}">
    {% for order_goods in evaluate_order.ordergoods_set.all %}
    <div style="margin-bottom:40px;">
      <table class="order_list_table w980">
        <tbody>
          <tr>
            <td width="55%">
              <ul class="order_goods_list clearfix">
                <li class="col01"><a href="{% url 'goods:detail' order_goods.sku.id %}"><img src="{{order_goods.sku.image.url}}"></a></li>
                <li class="col02">{{order_goods.sku.name}}<em>{{order_goods.sku.price}}元/{{order_goods.sku.unite}}</em></li>
                <li class="col03">{{order_goods.count}}</li>
                <li class="col04">{{order_goods.price}}元</li>
              </ul>
            </td>
            <td width="15%">{{order_goods.price}}元</td>
          </tr>
        </tbody>
      </table>
      <div style="display:flex; margin-top:20px;">
        <input type="hidden" name="order_goods_id_{{forloop.counter}}" value="{{order_goods.id}}">
        <label class="label_evaluate_title">评价内容</label>
        <textarea name="content_{{forloop.counter}}" cols="60" rows="6"></textarea>
      </div>
    </div>
    {% endfor %}
    <input type="submit" name="" value="提交" class="info_submit">
  </form>

</div>
{% endblock right_content %}
{% block bottomfiles %}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
		$(function(){
			console.log('enter evaluate order')
		})
	</script>
{% endblock bottomfiles %}